feat:トップページの作成
yuta10200831/7-4.docker-templete pull request #5
Opened 2023-09-06 02:28 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/4-b6f54e32fb2744439fb70312646d7840
[作成したページのURL(index.php)]
![スクリーンショット 2023-09-06 11 25 35](https://github.com/yuta10200831/7-4.docker-templete/assets/124555669/b5d365a9-779b-4a46-a974-d4ae3c667d63)

## 作業詳細
トップページの作成

2023-09-06 05:05 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-06 05:05 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +// 検索機能
検索機能は、仕様書にないので関係のないコードは削除しましょう！！
メモアプリからコピペしてそうですね！！そのような作業の仕方は素晴らしいです！
似たコードをコピペで使用し、いらない箇所を削除したり、必要な機能追加をするのがエンジニアの仕事です！

2023-09-06 14:02 UTC, yuta10200831 commented
レビューありがとうございます！
修正しましたのでご確認宜しくお願い致します。

2023-09-07 05:07 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-07 06:18 UTC, merged